### ISSUE TITLE
Broken table file?

### ISSUE THREAD

**Issue by MetaNite64** [ShaffyYoutube/RhythmTengokuENPatch#6]
When I try to compile from source, I get an error during the Atlas portion of compilation: 
`Error: The table file 'sjis_2.tbl' could not be opened on line 15`
Outdated (keeping for posterity): I'm looking into this at the moment, and I'll submit a pull request once I figure out what the correct path is (I think I might've found it, but now it's hanging after parsing and I don't know whether it's just taking a long time or it's broken in another spot).

Update: I literally undid the recent commit thinking it would fix it. Now that I feel stupid, I don't know what's happening. I'll add a bit more detail: compile.bat still says it completes successfully, but running the patched ROM just gives me a white screen that immediately fades to black.

**Comment by MetaNite64** [comment]
New update: I'm unable to get any debug output out of Atlas at all. Not through `-d stdout`, not through `-d debug.log`, nothing. It just gives me an empty file in the latter case. Frustrating >:(

**Comment by danylopez123** [comment]
Im also getting the same table error.
For me, the game still runs fine, ecept that like the health screen, title screen and main menu got translated ecept for the rest of the other texts which still remains in Japanese, not even the Debug menu got translated.
